server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

# 设置 Feign 客户端超时时间(OpenFeign 默认支持 Ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # 结合配置类，指定 Feign 日志以什么级别监控哪个接口，以 debug 形式打印它的 FULL 级别的日志
    study.qi.openfeign.service.PaymentFeignService: debug