server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:com:7001/eureka
    # 注册进 Eureka
    register-with-eureka: true
    fetch-registry: true